package com.patrick.delivery.controllers.api;

import com.fasterxml.jackson.databind.JsonNode;
import com.patrick.delivery.services.ApiOrderService;
import com.patrick.delivery.utils.ApiAbstractController;
import com.patrick.delivery.utils.ResponseModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

/**
 * @author patrick on 9/8/20
 * @project sprintel-delivery
 */
@RestController
@RequestMapping("/api/v1/order")
public class ApiOrderController extends ApiAbstractController {

    @Autowired
    private ApiOrderService apiOrderService;

    @GetMapping("/track")
    public ResponseModel trackOrders(@RequestParam(value = "orderNo") Long orderNo) {
        ResponseModel response;
        try {
            response = apiOrderService.trackOrder(orderNo);
        } catch (Exception e) {
            return apiError("/track", getObjectMapper().convertValue(orderNo, JsonNode.class), e);
        }
        return apiLogger("/track", getObjectMapper().convertValue(orderNo, JsonNode.class), response);

    }

    /**
     * Called to render the response as generated by the class item
     *
     * @param url
     * @param request
     * @param response
     * @return ResponseModel
     */
    protected ResponseModel apiLogger(String url, JsonNode request, ResponseModel response) {
        return super.apiLogger("/api/v1/order" + url, filterRequest(request, ""), response);
    }

    /**
     * Called to render the response as generated by the class item
     *
     * @param url
     * @param request
     * @param ex
     * @return ResponseModel
     */
    protected ResponseModel apiError(String url, JsonNode request, Exception ex) {
        return super.apiError("/api/v1/order" + url, filterRequest(request, ""), ex);
    }
}
