apiVersion: v1
kind: Service
metadata:
  name: sprintel-delivery-api-service
spec:
  selector:
    app: sprintel-delivery-api
  ports:
    - protocol: TCP
      port: 9090
      nodePort: 30007
  type: NodePort
